# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mission_export_format.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MissionFormat_Dialog(object):
    def setupUi(self, MissionFormat_Dialog):
        MissionFormat_Dialog.setObjectName("MissionFormat_Dialog")
        MissionFormat_Dialog.resize(394, 120)
        self.gridLayout = QtWidgets.QGridLayout(MissionFormat_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.SHP_checkBox = QtWidgets.QCheckBox(MissionFormat_Dialog)
        self.SHP_checkBox.setChecked(True)
        self.SHP_checkBox.setObjectName("SHP_checkBox")
        self.gridLayout.addWidget(self.SHP_checkBox, 0, 1, 1, 1)
        self.GPKG_checkBox = QtWidgets.QCheckBox(MissionFormat_Dialog)
        self.GPKG_checkBox.setChecked(True)
        self.GPKG_checkBox.setTristate(False)
        self.GPKG_checkBox.setObjectName("GPKG_checkBox")
        self.gridLayout.addWidget(self.GPKG_checkBox, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.create_pushButton = QtWidgets.QPushButton(MissionFormat_Dialog)
        self.create_pushButton.setObjectName("create_pushButton")
        self.horizontalLayout_4.addWidget(self.create_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(MissionFormat_Dialog)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout_4.addWidget(self.cancel_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(MissionFormat_Dialog)
        QtCore.QMetaObject.connectSlotsByName(MissionFormat_Dialog)

    def retranslateUi(self, MissionFormat_Dialog):
        _translate = QtCore.QCoreApplication.translate
        MissionFormat_Dialog.setWindowTitle(_translate("MissionFormat_Dialog", "Mission export format"))
        self.SHP_checkBox.setText(_translate("MissionFormat_Dialog", "Bloody Shapefile"))
        self.GPKG_checkBox.setText(_translate("MissionFormat_Dialog", "Geopackage"))
        self.create_pushButton.setText(_translate("MissionFormat_Dialog", "Create"))
        self.cancel_pushButton.setText(_translate("MissionFormat_Dialog", "Cancel"))
