[project]
name = "qgis-plugin-seacat-mission-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pyqt5>=5.15.11",
    "pyside6>=6.9.1",
    "shapely>=2.1.1",
]
